### ISSUE TITLE
When running the download script, it doesn't download all container images as follows.

### ISSUE THREAD

**Issue by WalongE** [kubespray-offline/kubespray-offline#35]
It doesn't download all container images as shown in the figure below.
Furthermore, the download script stops midway through execution as follows.

![1](https://github.com/kubespray-offline/kubespray-offline/assets/71746873/7bc42fae-9088-4480-ab05-728bad4d3b81)
![image](https://github.com/kubespray-offline/kubespray-offline/assets/71746873/9f7fd3b5-bad2-4688-8d3d-c62695f6d3de)

==> Pull quay.io/external_storage/cephfs-provisioner:v2.1.0-k8s1.11
v2.1.0-k8s1.11: Pulling from external_storage/cephfs-provisioner
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/external_storage/cephfs-provisioner:v2.1.0-k8s1.11 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
Failed in : ./download-kubespray-files.sh

Could you provide the solution?

**Comment by tmurakam** [comment]
It seems that the latest docker can't pull older format container images.
I think you can use nerdctl instead of docker.

**Comment by tmurakam** [comment]
Fixed.
