### ISSUE TITLE
Unable to find the appropriate versions of requirements.txt for Redhat.

### ISSUE THREAD

**Issue by vveldand** [kubespray-offline/kubespray-offline#39]
Hi @tmurakam 
Appreciate your contribution. 

I'm using Redhat 8.7 and have cloned the offline installer from the tag v2.24.1-1. The intention is to go with kubespray 2.24.1
The requirements.txt contains Ansible==8.5.0 which Redhat can't find and list various other versions to install. 
**_No matching distribution found for ansible==8.5.0_**

The closest I could find is version 9.0.0 which I could install. Now, once this is installed, it automatically tries to install ansible-core 2.16.0 and couldn't find this. The closest seems to be 2.11.12 but it isn't compatible with Ansible 9.0.0
**_ERROR: No matching distribution found for ansible-core~=2.16.0_**

**_ERROR: Cannot install -r requirements.txt (line 1) and ansible-core==2.11.12 because these package versions have conflicting dependencies._**

The conflict is caused by:
    The user requested ansible-core==2.11.12
    ansible 9.0.0 depends on ansible-core~=2.16.0

What is the recommendation here?. If I leave the versions empty in the requirements.txt ansible installs 4.x and the dependency ansible-core. Should this be the right approach?

**Comment by tmurakam** [comment]
Which version of Python do you use?
You must install and use python3.9 on RHEL8.x.

**Comment by vveldand** [comment]
Yes, it selects python3.9 as part of the VENV but it cannot find ansible 8.5.0. Should RHEL8 find 8.5.0 ansible version automatically?. Also is v2.24.1-1 compatible with Ansible 4.x etc as Redhat seem to be installing 4.x ansible version by default?

**Comment by tmurakam** [comment]
The OS version (RHEL 8) has nothing to do with the Python package version.
Only version of the Python is related.
