### ISSUE TITLE
Ports assigned to each of the register and nginx files sever

### ISSUE THREAD

**Issue by Noufel17** [kubespray-offline/kubespray-offline#44]
So as you can see here in the screenshot, both containers are running, but there is not port binding, I ran the offline playbook and I failed to update the cache for offline apt repository, file server is not reachable of course (VM that runs the container is in the same network), did I make a mistake? are the ports not exposed by default? I need some help
![image](https://github.com/user-attachments/assets/d66ca8ba-270d-49f3-96dd-9ad0b1d24d25)

**Comment by tmurakam** [comment]
They are running in host network mode (--network host), so you don't need port forwarding.

**Comment by Noufel17** [comment]
Okey thank you, what are the default ports, I recon 35000 for the register, and can be changed in config.sh, but I can't find the one for the nginx server.

**Comment by tmurakam** [comment]
Port 80 for nginx.
See https://hub.docker.com/_/nginx

**Comment by Noufel17** [comment]
Sorry for bothering you too much, I'm still having this issue when running the offline playbook that sets up the offline 
repository:
![image](https://github.com/user-attachments/assets/d3c7d569-da6c-4a0b-948d-707259c4a034)

I tried to curl the nginx server and got this:
![image](https://github.com/user-attachments/assets/9cb69dae-5e97-4b6c-974a-3f75cb540dc0)
